application: art-crime-archive
version: 0-1-6-test-id-links
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /static
  static_dir: static

- url: /ArchiveService.*
  script: services.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: lxml
  version: "2.3"

builtins:
- remote_api: on